source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/1358756992lijian/lijianPrivateSpecs.git'

# platform :ios, '8.0'

target 'LJKeyBroadEventManager' do
  # Comment the next line if you don't want to use dynamic frameworks
 

	pod 'LJKeyBroadEventManager', :path => '../'

pod 'LJViewKit', '~>2.4.0'


  # Pods for LJKeyBroadEventManager

end
