# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'LJKeyBroadEventManager' do
  # Comment the next line if you don't want to use dynamic frameworks
 

	pod 'LJKeyBroadEventManager', :path => '../'

  # Pods for LJKeyBroadEventManager

end
